# The URL the site will be built for
base_url = "https://swiftloke.github.io/reswitched-weekly-reboot.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
feed_filename = "rss.xml"
default_language = "en"
output_dir = "docs"
render_emoji = true
taxonomies = [
    {name = "tags"},
    {name = "categories", paginate_by=5},
    {name = "authors"}, 
]
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
